### ISSUE TITLE
Availability for send mails in a task system

### ISSUE THREAD

**Issue by eduherraiz** [APSL/django-yubin#14]
Leaving the dependecy of execute django commands in a cron system.

**Comment by Duologic** [comment]
I'm not using this library, just dropping my 2 cents here.

The description of this issue is quite limited, but as I understand, you'd simply want to enable cron scheduling with a task system? As celery is the defacto standard for Django, I'd assume you probably want to use that. 

I've done this process for other systems in the past, here is my take on this:

You can move the relevant code executed by the management command into a set of functions (for ex. in 'utils.py') and execute these functions from the management command to keep backwards compatibility.

If you got that right, you can also create `@shared_task` functions in 'tasks.py', which execute the functions from utils.py just like the management commands do. These tasks can then in turn be placed into a Celery Beat schedule of the Django project.

**Comment by Duologic** [comment]
I had a quick look and found an example for this: https://github.com/vikingco/django-mailer/pull/8

**Comment by sergei-maertens** [comment]
We have this hooked up via celery beat, see:

* https://github.com/open-formulieren/open-forms/blob/78e7ad6c0fd2b786c0387f584ec1d29d40095be4/src/openforms/conf/base.py#L635
* https://github.com/open-formulieren/open-forms/blob/78e7ad6c0fd2b786c0387f584ec1d29d40095be4/src/openforms/utils/tasks.py#L24

**Comment by sastred** [comment]
Hi all,

Sergei's solution is the right one for using the current stable version with a task system. In addition, there is a beta version of django-yubin that already works out of the box with Celery. Have a look at this comment for the details https://github.com/APSL/django-yubin/issues/62#issuecomment-1538016140.
